### ISSUE TITLE
FS: Main Dashboard Interviews Page

### ISSUE THREAD

**Issue by dahrk** [hatchways/team-all-bran#16]
- create the front-end UI for the main dashboard page - showing the past (and current) interview practices and the start button (we don't need a join button)
- The UI only shows past interviews, but we will show all of them ordered by most recent
- Modify the back-end to add a get all interviews route and display them on the page
- Will need to modify the back-end so that we have dates for each interview object

**Comment by kyi193** [comment]
I linked the PR and its been merged already
